[workspace]
resolver = "3"
members = [
  'apps/desktop',
  'crates/*',
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
gpui = "0.2.2"
serde = { version = "1", features = ["derive"] }
thiserror = "2"
bytemuck = { version = "1", features = ["derive"] }
wgpu = "25.0.2"
time = { path = "crates/time" }
decode = { path = "crates/decode" }
ids = { path = "crates/ids" }
clips = { path = "crates/clips" }
